from django import forms
class cyptForm(forms.Form):
    
    RadiusMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '17.98'}))
    TextureMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '10.38'}))
    PerimeterMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '122.7'}))
    AreaMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '1001'}))
    SmoothnessMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.1184'}))
    CompactnessMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.2776'}))
    ConcavityMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.3001'}))
    ConcavePointsMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.1471'}))
    SymmetryMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.2419'}))
    FractalDimensionMean = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.07871'}))
    RadiusSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '1.095'}))
    TextureSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.9053'}))
    PerimeterSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '8.589'}))
    AreaSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '153.4'}))
    SmoothnessSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.006399'}))
    CompactnessSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.04904'}))
    ConcavitySE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.05373'}))
    ConcavePointsSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.01587'}))
    SymmetrySE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.03003'}))
    FractalDimensionSE = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.006193'}))
    RadiusWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '25.38'}))
    TextureWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '17.33'}))
    PerimeterWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '184.6'}))
    AreaWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '2019'}))
    SmoothnessWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.1622'}))
    CompactnessWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.6656'}))
    ConcavityWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.7119'}))
    ConcavePointsWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.2654'}))
    SymmetryWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.4601'}))
    FractalDimensionWorst = forms.FloatField(label='', widget=forms.NumberInput(attrs={'placeholder': '0.1189'}))